name: HideAndSeek
version: '1.0'
main: me.vuxaer.hideandseek.HideAndSeekPlugin
api-version: '1.20'
authors: [ Vuxaer ]
description: A simple Hide and Seek minigame plugin

commands:
  hs:
    description: Main command for the Hide and Seek game
    usage: /hs <help|start|stop|reload|setspawn>
    permission: hs.admin
    permission-message: You do not have permission to use this command.

permissions:
  hs.admin:
    description: Allows managing the Hide and Seek game
    default: op